# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "master" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_LIGHTSAIL }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
 
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to Lightsail
      run: | 
        sudo apt-get install tmux
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.LIGHTSAIL_ADDRESS }}  << 'EOF'
        cd /var/www/tobacco_site/tobacco
         if ( sudo git pull || exit 1) | grep -q 'Already up to date'; then
          echo "No changes pulled. Skipping tmux commands."
           else
          DB_CONNECTION_STRING=${{ secrets.DB_CONNECTION_STRING }}
          tmux send-keys -t tobacco-site C-c Enter
          tmux send-keys -t tobacco-site "export DefaultConnection=\"$DB_CONNECTION_STRING\"" Enter
          tmux send-keys -t tobacco-site "dotnet 'Razor MVC project.dll'" Enter
           sleep 10  # Wait for application to start (adjust duration as needed)
           if pgrep -x "dotnet" > /dev/null; then
           echo "Application process is running."
            else
           echo "Error: Application process not found."
           exit 1  
           fi
         fi
        EOF
     
        
