# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Copy SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_LIGHTSAIL }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
 
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to Lightsail
      run: |
        sudo apt-get install tmux
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.LIGHTSAIL_ADDRESS }}  << 'EOF'
        cd /var/www/tobacco_site
        sudo git pull
         if sudo git pull | grep -q 'Already up to date'; then
          echo "No changes pulled. trying tmux commands anyway."
          tmux send-keys -t tobacco-site "echo Hello, world!" Enter
         else
          echo "tmux commands being run"
         fi
        EOF
        #tmux send-keys -t tobacco-site C-c Enter
        #tmux send-keys -t tobacco-site dotnet 'Razor MVC project.dll' Enter
        
